global proc AEVoxelSimulationNodeTemplate(string $nodeName)
{
    editorTemplate -beginScrollLayout;

    editorTemplate -label "Relaxation" -addControl "relaxation" ;
    editorTemplate -label "Edge Uniformity" -addControl "edgeUniformity";

    editorTemplate -suppress "frozen";
    editorTemplate -suppress "caching";
    editorTemplate -suppress "nodeState";

    editorTemplate -endScrollLayout;
}